package by.trjava.pashkovich.facultative.constants;

/**
 * Class contains all the SQL queries used used in the application
 * like public static final String fields.
 *
 * @author Katsiaryna Pashkovich
 * @version 1.0
 * @since JDK 1.0
 */
public class SqlQuery {
    //Queries for ApplyDAO
    public static final String INSERT_APPLY = "insert into applications values (?, ?, ?)";
    public static final String UPDATE_APPLY_STATUS = "update applications set applications.status_id = ? where user_id = ? and course_id = ?";
    public static final String DELETE_APPLY = "delete from applications where user_id = ? and course_id = ?";
    public static final String IS_CONTAINS_APPLY = "select * from applications where user_id = ? and course_id = ?";
    public static final String GET_APPLY_BY_STUDENT_RU = "select courses.course_id, courses.title_ru as title, categories.title_ru as category_title, concat(surname, ' ', name, ' ', patronymic) as teacher, number_of_classes, description_ru as description, statuses.title_ru as status, availability from applications inner join courses on applications.course_id = courses.course_id inner join statuses on applications.status_id = statuses.status_id inner join categories on categories.category_id = courses.category_id inner join user_details on courses.teacher_id = user_details.user_id where applications.status_id != 3 and applications.user_id = ?";
    public static final String GET_APPLY_BY_STUDENT_EN = "select courses.course_id, courses.title_en as title, categories.title_en as category_title, concat(surname, ' ', name, ' ', patronymic) as teacher, number_of_classes, description_en as description, statuses.title_en as status, availability from applications inner join courses on applications.course_id = courses.course_id inner join statuses on applications.status_id = statuses.status_id inner join categories on categories.category_id = courses.category_id inner join user_details on courses.teacher_id = user_details.user_id where applications.status_id != 3 and applications.user_id = ?";
    public static final String GET_ALL_APPLY_RU = "select users.user_id, login, email, password, users.role_id, surname, name, patronymic, date_of_birth, address, phone, courses.course_id, courses.title_ru as title, categories.title_ru as category_title, (select concat(surname, ' ', name, ' ', patronymic) from user_details where user_details.user_id=courses.teacher_id) as teacher, number_of_classes, description_ru as description, statuses.title_ru as status, availability from applications inner join courses on applications.course_id = courses.course_id inner join statuses on applications.status_id = statuses.status_id inner join categories on categories.category_id = courses.category_id inner join user_details on applications.user_id = user_details.user_id inner join users on users.user_id = user_details.user_id where applications.status_id = 1 or applications.status_id = 2";
    public static final String GET_ALL_APPLY_EN = "select users.user_id, login, email, password, users.role_id, surname, name, patronymic, date_of_birth, address, phone, courses.course_id, courses.title_en as title, categories.title_en as category_title, (select concat(surname, ' ', name, ' ', patronymic) from user_details where user_details.user_id=courses.teacher_id) as teacher, number_of_classes, description_en as description, statuses.title_en as status, availability from applications inner join courses on applications.course_id = courses.course_id inner join statuses on applications.status_id = statuses.status_id inner join categories on categories.category_id = courses.category_id inner join user_details on applications.user_id = user_details.user_id inner join users on users.user_id = user_details.user_id where applications.status_id = 1 or applications.status_id = 2";
    public static final String GET_ALL_APPLY_BY_STUDENT_NAME_RU = "select users.user_id, login, email, password, users.role_id, surname, name, patronymic, date_of_birth, address, phone, courses.course_id, courses.title_ru as title, categories.title_ru as category_title, (select concat(surname, ' ', name, ' ', patronymic) from user_details where user_details.user_id=courses.teacher_id) as teacher, number_of_classes, description_ru as description, statuses.title_ru as status, availability from applications inner join courses on applications.course_id = courses.course_id inner join statuses on applications.status_id = statuses.status_id inner join categories on categories.category_id = courses.category_id inner join user_details on applications.user_id = user_details.user_id inner join users on users.user_id = user_details.user_id where (applications.status_id = 1 or applications.status_id = 2) and concat(user_details.surname,' ',user_details.name,' ',user_details.patronymic) like ?";
    public static final String GET_ALL_APPLY_BY_STUDENT_NAME_EN = "select users.user_id, login, email, password, users.role_id, surname, name, patronymic, date_of_birth, address, phone, courses.course_id, courses.title_en as title, categories.title_en as category_title, (select concat(surname, ' ', name, ' ', patronymic) from user_details where user_details.user_id=courses.teacher_id) as teacher, number_of_classes, description_en as description, statuses.title_en as status, availability from applications inner join courses on applications.course_id = courses.course_id inner join statuses on applications.status_id = statuses.status_id inner join categories on categories.category_id = courses.category_id inner join user_details on applications.user_id = user_details.user_id inner join users on users.user_id = user_details.user_id where (applications.status_id = 1 or applications.status_id = 2) and concat(user_details.surname,' ',user_details.name,' ',user_details.patronymic) like ?";
    public static final String GET_ALL_APPLY_BY_COURSE_TITLE_RU = "select users.user_id, login, email, password, users.role_id, surname, name, patronymic, date_of_birth, address, phone, courses.course_id, courses.title_ru as title, categories.title_ru as category_title, (select concat(surname, ' ', name, ' ', patronymic) from user_details where user_details.user_id=courses.teacher_id) as teacher, number_of_classes, description_ru as description, statuses.title_ru as status, availability from applications inner join courses on applications.course_id = courses.course_id inner join statuses on applications.status_id = statuses.status_id inner join categories on categories.category_id = courses.category_id inner join user_details on applications.user_id = user_details.user_id inner join users on users.user_id = user_details.user_id where (applications.status_id = 1 or applications.status_id = 2) and courses.title_ru like ?";
    public static final String GET_ALL_APPLY_BY_COURSE_TITLE_EN = "select users.user_id, login, email, password, users.role_id, surname, name, patronymic, date_of_birth, address, phone, courses.course_id, courses.title_en as title, categories.title_en as category_title, (select concat(surname, ' ', name, ' ', patronymic) from user_details where user_details.user_id=courses.teacher_id) as teacher, number_of_classes, description_en as description, statuses.title_en as status, availability from applications inner join courses on applications.course_id = courses.course_id inner join statuses on applications.status_id = statuses.status_id inner join categories on categories.category_id = courses.category_id inner join user_details on applications.user_id = user_details.user_id inner join users on users.user_id = user_details.user_id where (applications.status_id = 1 or applications.status_id = 2) and courses.title_en like ?";
    public static final String GET_REVIEW_ABOUT_STUDENT = "select review from archives where student_id = ? and course_id = ?";
    public static final String DELETE_LEARNING_APPLY = "delete from applications where course_id = ? and status_id = 3";

    //Queries for ArchiveDAO
    public static final String INSERT_ARCHIVE = "insert into archives(student_id, course_id, average_mark, start_date, end_date, review) values (?, ?, ?, ?, ?, ?)";
    public static final String IS_CONTAINS_ARCHIVE = "select * from archives where student_id = ? and course_id = ?";
    public static final String GET_ARCHIVE_COURSE_BY_STUDENT_RU = "select start_date, end_date, average_mark, courses.course_id, courses.title_ru as title, categories.title_ru as category_title, concat(surname, ' ', name, ' ', patronymic) as teacher, number_of_classes, description_ru as description, availability from courses inner join archives on courses.course_id = archives.course_id inner join categories on categories.category_id = courses.category_id inner join user_details on user_details.user_id = courses.teacher_id where student_id = ? and (select count(*) from applications where applications.user_id = ? and course_id=archives.course_id ) = 0";
    public static final String GET_ARCHIVE_COURSE_BY_STUDENT_EN = "select start_date, end_date, average_mark, courses.course_id, courses.title_en as title, categories.title_en as category_title, concat(surname, ' ', name, ' ', patronymic) as teacher, number_of_classes, description_en as description, availability from courses inner join archives on courses.course_id = archives.course_id inner join categories on categories.category_id = courses.category_id inner join user_details on user_details.user_id = courses.teacher_id where student_id = ? and (select count(*) from applications where applications.user_id = ? and course_id=archives.course_id ) = 0";
    public static final String UPDATE_REVIEW = "update archives set review = ? where student_id = ? and course_id = ?";
    public static final String UPDATE_ARCHIVE = "update archives set average_mark = ?, start_date = ?, end_date = ? where student_id = ? and course_id = ?";

    //Queries for ClassDAO
    public static final String INSERT_CLASS = "insert into classes(course_id, date_time) values(?, ?)";
    public static final String IS_CONTAINS_CLASS = "select * from classes where course_id = ? and date_time like ?";
    public static final String DELETE_CLASS_BY_COURSE = "delete from classes where course_id = ?";
    public static final String GET_CLASSES_COUNT_BY_COURSE = "select count(*) as count from classes where course_id = ?";
    public static final String GET_CLASS_BY_COURSE = "select date_time from classes where course_id = ?";
    public static final String GET_BEGIN_DATE_BY_COURSE = "select date_time as date from classes where course_id = ? order by date_time limit 1";
    public static final String GET_END_DATE_BY_COURSE = "select date_time as date from classes where course_id = ? order by date_time desc limit 1";

    //Queries for CourseDAO
    public static final String GET_ALL_COURSE_RU = "select course_id, courses.title_ru as title, categories.title_ru as category_title, concat(surname, ' ', name, ' ', patronymic) as teacher, number_of_classes, description_ru as description, availability from courses inner join users on users.user_id = courses.teacher_id inner join user_details on users.user_id = user_details.user_id inner join categories on courses.category_id = categories.category_id";
    public static final String GET_ALL_COURSE_EN = "select course_id, courses.title_en as title, categories.title_en as category_title, concat(surname, ' ', name, ' ', patronymic) as teacher, number_of_classes, description_en as description, availability from courses inner join users on users.user_id = courses.teacher_id inner join user_details on users.user_id = user_details.user_id inner join categories on courses.category_id = categories.category_id";
    public static final String GET_COURSE_BY_CATEGORY_RU = "select course_id, courses.title_ru as title, categories.title_ru as category_title, concat(surname, ' ', name, ' ', patronymic) as teacher, number_of_classes, description_ru as description, availability from courses inner join users on users.user_id = courses.teacher_id inner join user_details on users.user_id = user_details.user_id inner join categories on courses.category_id = categories.category_id where categories.title_ru = ?";
    public static final String GET_COURSE_BY_CATEGORY_EN = "select course_id, courses.title_en as title, categories.title_en as category_title, concat(surname, ' ', name, ' ', patronymic) as teacher, number_of_classes, description_en as description, availability from courses inner join users on users.user_id = courses.teacher_id inner join user_details on users.user_id = user_details.user_id inner join categories on courses.category_id = categories.category_id where categories.title_en = ?";
    public static final String GET_COURSE_BY_ID_RU = "select course_id, courses.title_ru as title, categories.title_ru as category_title, concat(surname, ' ', name, ' ', patronymic) as teacher, number_of_classes, description_ru as description, availability from courses inner join users on users.user_id = courses.teacher_id inner join user_details on users.user_id = user_details.user_id inner join categories on courses.category_id = categories.category_id where courses.course_id = ?";
    public static final String GET_COURSE_BY_ID_EN = "select course_id, courses.title_en as title, categories.title_en as category_title, concat(surname, ' ', name, ' ', patronymic) as teacher, number_of_classes, description_en as description, availability from courses inner join users on users.user_id = courses.teacher_id inner join user_details on users.user_id = user_details.user_id inner join categories on courses.category_id = categories.category_id where courses.course_id = ?";
    public static final String GET_COURSE_BY_PARTIAL_MATCH_TITLE_RU = "select course_id, courses.title_ru as title, categories.title_ru as category_title, concat(surname, ' ', name, ' ', patronymic) as teacher, number_of_classes, description_ru as description, availability from courses inner join users on users.user_id = courses.teacher_id inner join user_details on users.user_id = user_details.user_id inner join categories on courses.category_id = categories.category_id where courses.title_ru like ?";
    public static final String GET_COURSE_BY_PARTIAL_MATCH_TITLE_EN = "select course_id, courses.title_en as title, categories.title_en as category_title, concat(surname, ' ', name, ' ', patronymic) as teacher, number_of_classes, description_en as description, availability from courses inner join users on users.user_id = courses.teacher_id inner join user_details on users.user_id = user_details.user_id inner join categories on courses.category_id = categories.category_id where courses.title_en like ?";
    public static final String GET_COURSE_BY_TEACHER_RU = "select course_id, courses.title_ru as title, categories.title_ru as category_title, concat(surname, ' ', name, ' ', patronymic) as teacher, number_of_classes, description_ru as description, availability from courses inner join users on users.user_id = courses.teacher_id inner join user_details on users.user_id = user_details.user_id inner join categories on courses.category_id = categories.category_id where courses.teacher_id = ?";
    public static final String GET_COURSE_BY_TEACHER_EN = "select course_id, courses.title_en as title, categories.title_en as category_title, concat(surname, ' ', name, ' ', patronymic) as teacher, number_of_classes, description_en as description, availability from courses inner join users on users.user_id = courses.teacher_id inner join user_details on users.user_id = user_details.user_id inner join categories on courses.category_id = categories.category_id where courses.teacher_id = ?";
    public static final String GET_COURSE_REQUIREMENT_RU = "select skills.title_ru as skill, levels.title_ru as level from requirements inner join levels on levels.level_id = requirements.level_id inner join skills on skills.skill_id = requirements.skill_id where course_id = ?";
    public static final String GET_COURSE_REQUIREMENT_EN = "select skills.title_en as skill, levels.title_en as level from requirements inner join levels on levels.level_id = requirements.level_id inner join skills on skills.skill_id = requirements.skill_id where course_id = ?";
    public static final String GET_COURSE_TIMETABLE_RU = "select title_ru as day, time from timetables inner join days on days.day_id = timetables.day_of_week where course_id = ?";
    public static final String GET_COURSE_TIMETABLE_EN = "select title_en as day, time from timetables inner join days on days.day_id = timetables.day_of_week where course_id = ?";
    public static final String GET_STUDENT_CURRENT_COURSE_RU = "select (select date_time from classes where course_id = works.course_id order by date_time desc limit 1) as start_date, courses.course_id, courses.title_ru as title, categories.title_ru as category_title, concat(surname, ' ', name, ' ', patronymic) as teacher, number_of_classes, description_ru as description, availability, (select avg(mark) from marks inner join works on works.work_id = marks.work_id where student_id = ? and course_id = courses.course_id) as mark from applications inner join courses on courses.course_id = applications.course_id inner join user_details on user_details.user_id = courses.teacher_id inner join categories on categories.category_id = courses.category_id left join works on works.course_id = courses.course_id left join marks on works.work_id = marks.work_id where applications.user_id = ? and status_id = 3 group by applications.course_id";
    public static final String GET_STUDENT_CURRENT_COURSE_EN = "select (select date_time from classes where course_id = works.course_id order by date_time desc limit 1) as start_date, courses.course_id, courses.title_en as title, categories.title_en as category_title, concat(surname, ' ', name, ' ', patronymic) as teacher, number_of_classes, description_en as description, availability, (select avg(mark) from marks inner join works on works.work_id = marks.work_id where student_id = ? and course_id = courses.course_id) as mark from applications inner join courses on courses.course_id = applications.course_id inner join user_details on user_details.user_id = courses.teacher_id inner join categories on categories.category_id = courses.category_id left join works on works.course_id = courses.course_id left join marks on works.work_id = marks.work_id where applications.user_id = ? and status_id = 3 group by applications.course_id";
    public static final String IS_COURSE_FIXED_FOR_TEACHER = "select * from courses where course_id = ? and teacher_id = ?";
    public static final String GET_COURSE_ID_BY_RU_TITLE = "select course_id from courses where title_ru = ?";
    public static final String GET_COURSE_ID_BY_EN_TITLE = "select course_id from courses where title_en = ?";
    public static final String GET_ALL_DAYS_RU = "select title_ru as title from days";
    public static final String GET_ALL_DAYS_EN = "select title_en as title from days";
    public static final String INSERT_COURSE = "insert into courses(title_ru, title_en, teacher_id, number_of_classes, category_id, availability, description_ru, description_en) values (?, ?, ?, ?, ?, ?, ?, ?)";
    public static final String INSERT_TIMETABLE_ELEMENT_RU = "insert into timetables values (?, (select day_id from days where title_ru = ?), ?)";
    public static final String INSERT_TIMETABLE_ELEMENT_EN = "insert into timetables values (?, (select day_id from days where title_en = ?), ?)";
    public static final String INSERT_REQUIREMENT_ELEMENT_RU = "insert into requirements values (?, (select skill_id from skills where title_ru = ?), (select level_id from levels where title_ru = ?))";
    public static final String INSERT_REQUIREMENT_ELEMENT_EN = "insert into requirements values (?, (select skill_id from skills where title_en = ?), (select level_id from levels where title_en = ?))";

    //Queries for MarkDAO
    public static final String INSERT_MARK = "insert into marks(student_id, work_id, mark) values (?, ?, ?)";
    public static final String UPDATE_MARK = "update marks set mark = ? where student_id = ? and work_id = ?";
    public static final String DELETE_MARK_BY_COURSE = "delete marks from marks inner join works on works.work_id=marks.work_id where course_id = ?";
    public static final String GET_STUDENT_AVERAGE_MARK_BY_COURSE = "select avg(mark) as mark from marks inner join works on works.work_id = marks.work_id where student_id = ? and course_id = ?";
    public static final String GET_STUDENT_ALL_MARK_BY_COURSE = "select title, mark from marks inner join works on works.work_id = marks.work_id where student_id = ? and course_id = ?";
    public static final String GET_STUDENT_MARK_BY_COURSE = "select mark from marks inner join works on works.work_id = marks.work_id where student_id = ? and course_id = ?";
    public static final String GET_STUDENT_WITH_MARK_BY_COURSE_WORK = "select users.user_id, login, email, password, surname, name, patronymic, date_of_birth, address, phone, users.role_id, mark from users left join user_details on user_details.user_id = users.user_id left join positions on user_details.position = positions.position_id inner join marks on marks.student_id = users.user_id inner join works on works.work_id = marks.work_id where course_id = ? and works.title=?";

    //Queries for UserDAO
    public static final String INSERT_USER = "insert into users(login, email, password, role_id) values (?, ?, ?, ?)";
    public static final String INSERT_USER_DETAILS = "insert into user_details(user_id, surname, name, patronymic, phone, address, date_of_birth, position) values(?, ?, ?, ?, ?, ?, ?, ?)";
    public static final String UPDATE_USER_DETAILS = "update user_details set surname=?, name=?, patronymic=?, phone=?, date_of_birth=?, address=?, position=? where user_id = ?";
    public static final String GET_USER_BY_LOGIN_RU = "select users.user_id, login, email, password, surname, name, patronymic, date_of_birth, address, phone, positions.title_ru as position, users.role_id from users left join user_details on user_details.user_id = users.user_id left join positions on user_details.position = positions.position_id where login = ?";
    public static final String GET_USER_BY_LOGIN_EN = "select users.user_id, login, email, password, surname, name, patronymic, date_of_birth, address, phone, positions.title_en as position, users.role_id from users left join user_details on user_details.user_id = users.user_id left join positions on user_details.position = positions.position_id where login = ?";
    public static final String GET_USER_BY_EMAIL_RU = "select users.user_id, login, email, password, surname, name, patronymic, date_of_birth, address, phone, positions.title_ru as position, users.role_id from users left join user_details on user_details.user_id = users.user_id left join positions on user_details.position = positions.position_id where email = ?";
    public static final String GET_USER_BY_EMAIL_EN = "select users.user_id, login, email, password, surname, name, patronymic, date_of_birth, address, phone, positions.title_en as position, users.role_id from users left join user_details on user_details.user_id = users.user_id left join positions on user_details.position = positions.position_id where email = ?";
    public static final String GET_USER_BY_ID_RU = "select users.user_id, login, email, password, surname, name, patronymic, date_of_birth, address, phone, positions.title_ru as position, users.role_id from users left join user_details on user_details.user_id = users.user_id left join positions on user_details.position = positions.position_id where users.user_id = ?";
    public static final String GET_USER_BY_ID_EN = "select users.user_id, login, email, password, surname, name, patronymic, date_of_birth, address, phone, positions.title_en as position, users.role_id from users left join user_details on user_details.user_id = users.user_id left join positions on user_details.position = positions.position_id where users.user_id = ?";
    public static final String GET_PASSWORD_BY_LOGIN = "select password from users where login = ?";
    public static final String IS_CONTAINS_USER_DETAILS_BY_LOGIN = "select login from users inner join user_details on users.user_id = user_details.user_id where login = ?";
    public static final String GET_ALL_STUDENT_BY_COURSE = "select users.user_id, login, email, password, users.role_id, surname, name, patronymic, date_of_birth, address, phone from applications inner join statuses on applications.status_id = statuses.status_id inner join users on users.user_id = applications.user_id inner join user_details on user_details.user_id = applications.user_id where applications.status_id = 3 and course_id = ?";
    public static final String GET_ALL_STUDENT = "select users.user_id, login, email, password, users.role_id, surname, name, patronymic, date_of_birth, address, phone from users inner join roles on users.role_id = roles.role_id inner join user_details on user_details.user_id = users.user_id where users.role_id = 3";
    public static final String GET_STUDENT_BY_PARTIAL_MATCH = "select users.user_id, login, email, password, users.role_id, surname, name, patronymic, date_of_birth, address, phone from users inner join roles on users.role_id = roles.role_id inner join user_details on user_details.user_id = users.user_id where users.role_id = 3 and concat(surname, ' ', name, ' ', patronymic) like ?";
    public static final String GET_ALL_TEACHER_WITH_COURSE_COUNT_RU = "select users.user_id, login, email, password, users.role_id, surname, name, patronymic, positions.title_ru as position, phone, count(course_id) as count from users inner join roles on users.role_id = roles.role_id inner join user_details on user_details.user_id = users.user_id inner join courses on courses.teacher_id = users.user_id inner join positions on positions.position_id = user_details.position where users.role_id = 2 group by users.user_id";
    public static final String GET_ALL_TEACHER_WITH_COURSE_COUNT_EN = "select users.user_id, login, email, password, users.role_id, surname, name, patronymic, positions.title_en as position, phone, count(course_id) as count from users inner join roles on users.role_id = roles.role_id inner join user_details on user_details.user_id = users.user_id inner join courses on courses.teacher_id = users.user_id inner join positions on positions.position_id = user_details.position where users.role_id = 2 group by users.user_id";
    public static final String GET_TEACHER_BY_PARTIAL_MATCH_RU = "select users.user_id, login, email, password, users.role_id, surname, name, patronymic, positions.title_ru as position, phone, count(course_id) as count from users inner join roles on users.role_id = roles.role_id inner join user_details on user_details.user_id = users.user_id inner join courses on courses.teacher_id = users.user_id inner join positions on positions.position_id = user_details.position where users.role_id = 2 and concat(surname, ' ', name, ' ', patronymic) like ? group by users.user_id";
    public static final String GET_TEACHER_BY_PARTIAL_MATCH_EN = "select users.user_id, login, email, password, users.role_id, surname, name, patronymic, positions.title_en as position, phone, count(course_id) as count from users inner join roles on users.role_id = roles.role_id inner join user_details on user_details.user_id = users.user_id inner join courses on courses.teacher_id = users.user_id inner join positions on positions.position_id = user_details.position where users.role_id = 2 and concat(surname, ' ', name, ' ', patronymic) like ? group by users.user_id";
    public static final String GET_ALL_TEACHER_RU = "select users.user_id, login, email, password, users.role_id, surname, name, patronymic, phone, positions.title_ru as position from users inner join roles on users.role_id = roles.role_id inner join user_details on user_details.user_id = users.user_id inner join positions on positions.position_id = user_details.position where users.role_id = 2";
    public static final String GET_ALL_TEACHER_EN = "select users.user_id, login, email, password, users.role_id, surname, name, patronymic, phone, positions.title_en as position from users inner join roles on users.role_id = roles.role_id inner join user_details on user_details.user_id = users.user_id inner join positions on positions.position_id = user_details.position where users.role_id = 2";

    //Queries for WorkDAO
    public static final String INSERT_WORK = "insert into works(course_id, title) values (?, ?)";
    public static final String DELETE_WORK_BY_COURSE = "delete from works where course_id = ?";
    public static final String GET_WORK_TITLE_BY_COURSE = "select title from works where course_id = ?";
    public static final String GET_WORK_ID = "select work_id from works where course_id = ? and title = ?";
    public static final String IS_WORK_AVAILABLE_FOR_TEACHER = "select * from works inner join courses on courses.course_id = works.course_id where teacher_id = ? and work_id = ?";
    public static final String IS_WORK_AVAILABLE_FOR_STUDENT = "select * from works inner join courses on courses.course_id = works.course_id inner join applications on applications.course_id = courses.course_id where applications.user_id = ? and work_id = ? and status_id = 3";

    //Queries for SkillDAO
    public static final String GET_ALL_SKILL_WITH_COURSE_COUNT_RU = "select title_ru as title, count(course_id) as count from requirements inner join skills on skills.skill_id = requirements.skill_id group by title";
    public static final String GET_ALL_SKILL_WITH_COURSE_COUNT_EN = "select title_en as title, count(course_id) as count from requirements inner join skills on skills.skill_id = requirements.skill_id group by title";
    public static final String GET_ALL_SKILL_RU = "select title_ru as title from skills";
    public static final String GET_ALL_SKILL_EN = "select title_en as title from skills";
    public static final String GET_ALL_SKILL_LEVEL_RU = "select title_ru as title from levels";
    public static final String GET_ALL_SKILL_LEVEL_EN = "select title_en as title from levels";

    //Queries for CategoryDAO
    public static final String GET_ALL_CATEGORY_WITH_COURSE_COUNT_RU = "select categories.title_ru as title, count(course_id) as count from categories inner join courses on categories.category_id = courses.category_id group by title";
    public static final String GET_ALL_CATEGORY_WITH_COURSE_COUNT_EN = "select categories.title_en as title, count(course_id) as count from categories inner join courses on categories.category_id = courses.category_id group by title";
    public static final String GET_ALL_CATEGORY_RU = "select title_ru as title from categories";
    public static final String GET_ALL_CATEGORY_EN = "select title_en as title from categories";
    public static final String GET_CATEGORY_BY_TITLE_RU = "select category_id from categories where title_ru = ?";
    public static final String GET_CATEGORY_BY_TITLE_EN = "select category_id from categories where title_en = ?";

}