package by.trjava.pashkovich.facultative.controller.command.variety;

public enum CommandVariety {
    LOGIN, LOGOUT, REGISTRATION, ACCOUNT, EDIT_STUDENT, EDIT_STUDENT_FORM, VIEW_ALL_COURSE, SEARCH_COURSE,
    VIEW_COURSE_INFO, APPLY, CURRENT_COURSE, FIXED_COURSE, ADD_CLASS, ADD_CLASS_FORM, ADD_WORK, ADD_WORK_FORM,
    CHANGE_LANGUAGE
}
